spring:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    ddl-auto: create

roomescape:
  auth:
    jwt:
      secret: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
      expiration: 1800000
